# Phần 1: Khám phá Tensor 

## Task 1.1 Tạo Tensor 

In [1]:
import torch 
import numpy as np

In [2]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
print(f"Tensor from list:\n {x_data} \n")

Tensor from list:
 tensor([[1, 2],
        [3, 4]]) 



In [3]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(f"Tensor from NumPy array:\n {x_np} \n")

Tensor from NumPy array:
 tensor([[1, 2],
        [3, 4]], dtype=torch.int32) 



In [4]:
x_ones = torch.ones_like(x_data)
print(f"Tensor of ones like x_data:\n {x_ones} \n")

Tensor of ones like x_data:
 tensor([[1, 1],
        [1, 1]]) 



In [5]:
x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f"Random tensor like x_data:\n {x_rand} \n")

Random tensor like x_data:
 tensor([[0.3172, 0.3338],
        [0.6064, 0.9552]]) 



In [6]:
print("Shape of tensor:", x_rand.shape)
print("Datatype of tensor:", x_rand.dtype)
print("Device tensor is stored on:", x_rand.device)

Shape of tensor: torch.Size([2, 2])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## Task 1.2: Các phép toán trên Tensor 

In [7]:
x_data + x_data

tensor([[2, 4],
        [6, 8]])

In [8]:
x_data * 5 

tensor([[ 5, 10],
        [15, 20]])

In [9]:
x_data @ x_data.T

tensor([[ 5, 11],
        [11, 25]])

## Task 1.3 Indexing and Slicing 

In [ ]:
# First row 
x_data[0]

tensor([1, 2])

In [11]:
# Second column
x_data[:, 1]

tensor([2, 4])

In [12]:
x_data[1, 1]

tensor(4)

## Task 1.4 

In [ ]:
x_rand = torch.rand((4, 4))
print(f"Random Tensor:\n {x_rand} \n")
x_rand.shape 

Random Tensor:
 tensor([[0.1984, 0.2934, 0.3363, 0.3253],
        [0.6890, 0.7847, 0.4712, 0.8304],
        [0.9592, 0.4035, 0.8865, 0.0031],
        [0.9849, 0.6022, 0.0160, 0.7509]]) 



torch.Size([4, 4])

In [14]:
x_rand_reshape = x_rand.reshape((16, 1))
print(f"Reshaped Tensor:\n {x_rand_reshape} \n")
x_rand_reshape.shape

Reshaped Tensor:
 tensor([[0.1984],
        [0.2934],
        [0.3363],
        [0.3253],
        [0.6890],
        [0.7847],
        [0.4712],
        [0.8304],
        [0.9592],
        [0.4035],
        [0.8865],
        [0.0031],
        [0.9849],
        [0.6022],
        [0.0160],
        [0.7509]]) 



torch.Size([16, 1])

# Phần 2: Tự động tính Đạo hàm với autograd 

## Task 2.1 Thực hành với `autograd`

In [15]:
# Tạo một tensor và yêu cầu tính đạo hàm cho nó
x = torch.ones(1, requires_grad=True)
print(f"x: {x}")

# Thực hiện một phép toán
y = x + 2
print(f"y: {y}")

# y được tạo ra từ một phép toán có x, nên nó cũng có grad_fn
print(f"grad_fn của y: {y.grad_fn}")

# Thực hiện thêm các phép toán
z = y * y * 3

# Tính đạo hàm của z theo x
z.backward() # tương đương z.backward(torch.tensor(1.))

# Đạo hàm được lưu trong thuộc tính .grad
# Ta có z = 3 * (x+2)^2 => dz/dx = 6 * (x+2). Với x=1, dz/dx = 18
print(f"Đạo hàm của z theo x: {x.grad}")

x: tensor([1.], requires_grad=True)
y: tensor([3.], grad_fn=<AddBackward0>)
grad_fn của y: <AddBackward0 object at 0x000002DD431C3940>
Đạo hàm của z theo x: tensor([18.])


In [ ]:
z.backward()  # Tính đạo hàm lần nữa mà không reset
print(f"Đạo hàm của z theo x sau lần backward thứ hai: {x.grad}")
# Báo lỗi vì đồ thị tính toán đã bị giải phóng sau lần backward đầu tiên
# Nếu muốn tính lại, ta cần đặt retain_graph=True trong lần backward đầu tiên

RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.

# Phần 3: Xây dựng Mô hình đầu tiên với `torch.nn`
`torch.nn` là module cung cấp các lớp và công cụ để xây dựng mạng nơ-ron.

## Task 3.1 Lớp `nn.Linear`
Lớp `nn.Linear` thực hiện một phép biến đổi tuyến tính `y = xA^T + b`.

In [17]:
# Khởi tạo một lớp Linear biến đổi từ 5 chiều -> 2 chiều
linear_layer = torch.nn.Linear(in_features=5, out_features=2)

# Tạo một tensor đầu vào mẫu
input_tensor = torch.randn(3, 5) # 3 mẫu, mỗi mẫu 5 chiều

# Truyền đầu vào qua lớp linear
output = linear_layer(input_tensor)

print(f"Input shape: {input_tensor.shape}")
print(f"Output shape: {output.shape}")
print(f"Output:\n {output}")

Input shape: torch.Size([3, 5])
Output shape: torch.Size([3, 2])
Output:
 tensor([[0.1762, 0.4418],
        [0.6236, 0.5600],
        [0.0888, 0.4620]], grad_fn=<AddmmBackward0>)


## Task 3.2 Lớp nn.Embedding 
Lớp `nn.Embedding` là một bảng tra cứu, dùng để ánh xạ các chỉ số của từ thành các vector embedding.

In [18]:
# Khởi tạo lớp Embedding cho một từ điển 10 từ, mỗi từ biểu diễn bằng vector 3 chiều
embedding_layer = torch.nn.Embedding(num_embeddings=10, embedding_dim=3)

# Tạo một tensor đầu vào chứa các chỉ số của từ (ví dụ: một câu)
# Các chỉ số phải nhỏ hơn 10
input_indices = torch.LongTensor([1, 5, 0, 8])

# Lấy ra các vector embedding tương ứng
embeddings = embedding_layer(input_indices)

print(f"Input shape: {input_indices.shape}")
print(f"Output shape: {embeddings.shape}")
print(f"Embeddings:\n {embeddings}")

Input shape: torch.Size([4])
Output shape: torch.Size([4, 3])
Embeddings:
 tensor([[ 0.0540,  1.3779, -0.2905],
        [ 0.8969, -0.1898,  0.0027],
        [-1.9983, -0.6767,  1.4691],
        [-1.9741, -0.3000, -0.1893]], grad_fn=<EmbeddingBackward0>)


## Task 3.3 Kết hợp thành một `nn.Module`
Đây là cách chuẩn để định nghĩa một mô hình trong PyTorch 

In [19]:
from torch import nn 

class MyFirstModel(nn.Module): 
  def __init__(self, vocab_size, embedding_dim, hidden_dim, output_dim):
    super(MyFirstModel, self).__init__()
    # Định nghĩa các lớp (layers)
    self.embedding = nn.Embedding(num_embeddings=vocab_size, embedding_dim=embedding_dim)
    self.linear = nn.Linear(in_features=embedding_dim, out_features=hidden_dim)
    self.activation = nn.ReLU()
    self.output_layer = nn.Linear(in_features=hidden_dim, out_features=output_dim)
  
  def forward(self, x):
    # Định nghĩa luồng dữ liệu (forward pass)
    # 1. Lấy embedding
    embeds = self.embedding(x)
    # 2. Truyeefn qua lớp linear và activation
    hidden = self.activation(self.linear(embeds))
    # 3. Lấy đầu ra cuối cùng
    output = self.output_layer(hidden)
    return output


In [20]:
model = MyFirstModel(vocab_size=100, embedding_dim=16, hidden_dim=8, output_dim=2)
input_data = torch.LongTensor([1, 2, 5, 9])  # một câu gồm 4 từ

output_data = model(input_data)
print(f"Output shape: {output_data.shape}")

Output shape: torch.Size([4, 2])
